### ISSUE TITLE
Refactor use of '$names' and how API objects get a reference to the actual object

### ISSUE THREAD

**Issue by alekhinen** [yeti/signals#23]
1. When the `Parser` gathers all of the different schema objects and endpoints, the endpoints still only hold the string that matches the name of the schema object, ex. `$postResponse`. When the templates go to render content later, they're constantly looking up `schema_objects[$postResponse] to get the right object. It might make more sense and be less brittle to set the schema objects on the endpoints during the Parsing phase.

2. Our current schema format, which wraps every schema object in another dictionary in order to quickly look up the key via `schema_objects[$objectName]` is unnecessary and makes our schema more cumbersome to write and parse. Also some of the naming, like `$postResponse` and `#meta` seem to be arbitrary and should all be standardized as just regular json.

**Comment by baylee** [comment]
I don't understand what this issue is referencing... Can someone add a little more to this ticket?

**Comment by rmutter** [comment]
@baylee done - also this relates to part of #15 concerning the "improving current schema" part of things. The idea is if we choose the write format it could work with existing tools to eventually be auto-generated.
