### ISSUE TITLE
Path to api schema file doesn't work with '~'

### ISSUE THREAD

**Issue by walkingtowork** [yeti/signals#43]
`~/projects/path/to/api-schema-1.0.json` fails with the following error: 
`Error: Path "~/projects/path/to/api-schema-1.0.json" does not exist.` 

`/Users/Alex/projects/path/to/api-schema-1.0.json` works as expected.

**Comment by rmutter** [comment]
Looks like we need to expand the path: http://stackoverflow.com/questions/2057045/python-os-makedirs-dont-understand-in-my-path
